openapi: 3.0.0
info:
    version: 1.0.0
    title: Dog Canine Shelter API
    description: Dog Canine Shelter API.
    contact:
        name: Master Chan
        email: 237049104@stu.vtc.edu.hk
    license:
        name: Apache 2.0
        url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
    - url: 'https://canine-shelter-dog-api.zeabur.app/'
      description: Development server
tags:
    - name: Auth
      description: API endpoints for user management
    - name: Dog
      description: Access and perform CRUD operations for dog
paths:
    /getDogInfo/?id={id}:
        parameters:
            - in: path
              name: id
              schema:
                  type: integer
              required: true
              description: Numeric id of the dog
        get:
            tags:
                - Dog
            description: get dog by id
            responses:
                '200':
                    description: View of a dog record
                '404':
                    description: Dog not found
    /getAllDogsInfo:
        get:
            tags:
                - Dog
            description: get all dog record
            responses:
                '200':
                    description: List of dogs record
                '404':
                    description: Dog record not found
    /addNewDogInfo:
        post:
            tags:
                - Dog
            description: Add a dog
            requestBody:
                description: Dog in JSON format
                required: true
                content:
                    application/json:
                        schema:
                            $ref: ./article.json#/definitions/article
            responses:
                '200':
                    description: Dog added
