openapi: 3.1.0
info:
    version: 1.0.0
    title: Dog Canine Shelter API
    description: Dog Canine Shelter API.
    contact:
        name: Master Harry Chan
        email: 237049104@stu.vtc.edu.hk
    license:
        name: Apache 2.0
        url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
    - url: 'https://canine-shelter-dog-api.zeabur.app/'
      description: Production server
    - url: 'wss://canine-shelter-dog-websocket.zeabur.app/'
      description: Production WebSocket signal
tags:
    - name: Auth
      description: API endpoints for user management
    - name: Dog
      description: Access and perform CRUD operations for dog
    - name: Favorites
      description: Access and perform CRUD operations for favorites
    - name: Chat
      description: Access and perform CRUD operations for chat room
    - name: WebSocket
      description: WebSocket signal
paths:
    /:
        post:
            requestBody:
                description: A message from the chat room
                content:
                    application/json:
                        schema:
                            $ref: ./chatMessage.json#/definitions/chatMessage
            responses:
                '200':
                    description: Message received by client
    /auth/login:
        post:
            tags:
                - Auth
            description: User login account
            requestBody:
                description: Login in JSON format
                required: true
                content:
                    application/json:
                        schema:
                            $ref: ./login.json#/definitions/login
            responses:
                '200':
                    description: Login success
                '400':
                    description: Login field missing
                '500':
                    description: Login fail
    /auth/registration:
        post:
            tags:
                - Auth
            description: User registration account
            requestBody:
                description: Registration in JSON format
                required: true
                content:
                    application/json:
                        schema:
                            $ref: ./registration.json#/definitions/registration
            responses:
                '200':
                    description: Registration success
                '400':
                    description: Registration field missing
                '500':
                    description: Registration fail
    /auth/roleQuery?email={email}:
        parameters:
            - in: query
              name: email
              schema:
                  type: string
              required: true
              description: Email of registered account
        get:
            tags:
                - Auth
            description: identify account is a staff account
            responses:
                '200':
                    description: Result of query
                '404':
                    description: Record not found
    /dog/getDogInfo?id={id}:
        parameters:
            - in: query
              name: id
              schema:
                  type: integer
              required: true
              description: Numeric id of the dog
        get:
            tags:
                - Dog
            description: get dog by id
            responses:
                '200':
                    description: View of a dog record
                '404':
                    description: Dog not found
    /dog/getAllDogsInfo:
        get:
            tags:
                - Dog
            description: get all dog record
            responses:
                '200':
                    description: List of dogs record
                '404':
                    description: Dog record not found
    /dog/addNewDogInfo:
        post:
            tags:
                - Dog
            description: Add a dog
            requestBody:
                description: Dog in JSON format
                required: true
                content:
                    application/json:
                        schema:
                            $ref: ./dog.json#/definitions/dog
            responses:
                '201':
                    description: Dog added
                '400':
                    description: Dog object field missing
                '500':
                    description: Added fail
    /dog/updateDogInfo:
        put:
            tags:
                - Dog
            description: Update a dog record
            requestBody:
                description: Dog in JSON format
                required: true
                content:
                    application/json:
                        schema:
                            $ref: ./dog.json#/definitions/dog
            responses:
                '200':
                    description: Dog updated
                '400':
                    description: Dog object field missing
                '500':
                    description: Update fail
    /dog/deleteDogInfo?id={id}:
        parameters:
            - in: query
              name: id
              schema:
                  type: integer
              required: true
              description: Numeric id of the dog
        delete:
            tags:
                - Dog
            description: delete dog by id
            responses:
                '200':
                    description: Dog deleted
                '500':
                    description: Delete fail
    /dog/uploadDogPhoto:
        post:
            tags:
                - Dog
            description: Upload a dog photo
            requestBody:
                description: Dog in JSON format
                required: true
                content:
                    application/json:
                        schema:
                            $ref: ./uploadFile.json#/definitions/uploadFile
            responses:
                '201':
                    description: Photo uploaded
                '400':
                    description: Upload file object field missing
                '500':
                    description: Upload fail
    /dog/getBreedsList:
        get:
            tags:
                - Dog
            description: get all dog breed
            responses:
                '200':
                    description: List of dogs breed
                '404':
                    description: Dog breed not found
    /dog/getBreedImg?breed={breed}:
        parameters:
            - in: query
              name: breed
              schema:
                  type: string
              required: true
              description: breed of the dog
        get:
            tags:
                - Dog
            description: get image of a dog by breed
            responses:
                '200':
                    description: Url of the dog image
                '404':
                    description: Dog image not found
    /dog/getDogWithList?id={id}:
        parameters:
            - in: query
              name: id
              schema:
                  type: number[]
              required: true
              description: List of the dog id
        get:
            tags:
                - Dog
            description: get dog info by list of id
            responses:
                '200':
                    description: List of dog info
                '404':
                    description: Dog info not found
    /favorites/getUserFavoritesList?email={email}:
        parameters:
            - in: query
              name: email
              schema:
                  type: string
              required: true
              description: Email of registered account
        get:
            tags:
                - Favorites
            description: get id list by registered account
            responses:
                '200':
                    description: List of dog id
                '404':
                    description: Record not found
    /favorites/addFavorite:
        post:
            tags:
                - Favorites
            description: Add a favorite
            requestBody:
                description: Favorite in JSON format
                required: true
                content:
                    application/json:
                        schema:
                            $ref: ./favorite.json#/definitions/favorite
            responses:
                '201':
                    description: Favorite added
                '400':
                    description: Favorite object field missing
                '500':
                    description: Added fail
    /favorites/deleteFavorite?email={email}&?id={id}:
        parameters:
            - in: query
              name: id
              schema:
                  type: integer
              required: true
              description: Numeric id of the dog
            - in: query
              name: email
              schema:
                  type: string
              required: true
              description: Email of registered account
        delete:
            tags:
                - Favorites
            description: delete favorite by dog id
            responses:
                '200':
                    description: Favorite deleted
                '500':
                    description: Delete fail
    /chat/getChatAllHistory:
        get:
            tags:
                - Chat
            description: get all chat room history
            responses:
                '200':
                    description: List of chat record
                '404':
                    description: Chat record not found
                    /dog/addNewDogInfo:
    /chat/addMessage:
        post:
            tags:
                - Chat
            description: Send a message to chat room
            requestBody:
                description: Chat message in JSON format
                required: true
                content:
                    application/json:
                        schema:
                            $ref: ./chatMessage.json#/definitions/chatMessage
            responses:
                '201':
                    description: Chat message sent
                '400':
                    description: Chat message object field missing
                '500':
                    description: Added fail
    /chat/updateMessage:
        put:
            tags:
                - Chat
            description: Update a chat message record
            requestBody:
                description: Chat message in JSON format
                required: true
                content:
                    application/json:
                        schema:
                            $ref: ./chatMessage.json#/definitions/chatMessage
            responses:
                '200':
                    description: Chat message updated
                '400':
                    description: Chat message object field missing
                '500':
                    description: Update fail
    /chat/deleteMessage?id={id}:
        parameters:
            - in: query
              name: id
              schema:
                  type: integer
              required: true
              description: Numeric id of the chat message
        delete:
            tags:
                - Chat
            description: delete chat message by id
            responses:
                '200':
                    description: Chat message deleted
                '500':
                    description: Delete fail
    /chat/uploadImage:
        post:
            tags:
                - Chat
            description: Upload a message photo
            requestBody:
                description: Chat message in JSON format
                required: true
                content:
                    application/json:
                        schema:
                            $ref: ./uploadFile.json#/definitions/uploadFile
            responses:
                '201':
                    description: Photo uploaded
                '400':
                    description: Upload file object field missing
                '500':
                    description: Upload fail
